version: '3'

services:
  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/app
    expose:
      - "80"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/archive/phankimngoc.online:/etc/ssl/private:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge