name: CI/CD Pipeline new

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/docker_/django_docker_repo
            git pull origin main
            docker-compose down
            docker rmi django_landingpage:latest || true
            docker-compose build --no-cache
            docker-compose up -d
            docker system prune -f