name: CI/CD Pipeline 01

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.159.223.49.206 }}
        username: ${{ secrets.root }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
            cd /home/docker_/django_docker_repo
            ls -la