name: CI/CD Pipeline 01

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.159.223.49.206 }}
        username: ${{ secrets.root }}
        key: ${{ secrets.-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: DES-EDE3-CBC,F42512AD2D8E5497

AhsVYj9qutejBj9g22tuiuV0tzQcPxWrBpqFe7tdlM+1dKNmXjjOoFEZJv1HWQrn
J2RbcF+TEfywmBn+dAY8nKYLyDbGN6Upz4RKaJgRumYvX7m6bbIxTamyK/t9k2+b
MlG4iruXtWmKJ3JHPwasXU6c/8KfnWo+Auw8w1WqpYEqRtbxamwh21NQ2HjmMJDU
CoXLiku1O7VhlJ6uXxGbEkZIRk7df1rzfkyHWf6XKiBvhJdD8azcNGwURQDwmGv+
H4jLPoTAJvHfZ6KdqcIz9phsXOc5Ey7xBm0sI2kLIJ3b1iMzcgJuMeCuEmw/nP08
ViSSsiMcwro1aPHktUVPWza9RvAGi/MsPA+dSrfzLcEz8exbbGr0u57fvBV8qGix
YVBburkUejA3b/O8xQT5802SUglpw2mNlbGA4Mx0m8aB7Mci42O/gsa8Dch2+K6j
Lm6tkKaHzKwr6YJp7qFAr0fzoKXCiaaiAlV2GnAGUxLFHz5a4ml6n5kYqSD+gYMi
A/IP6siU1o/cr+5WLjGeASZt4wRe7zyWA7c3TDSKIytfRPEYSfgMJcCSYYxxp9oL
TQW9j+lD1C/Akv2vZv0ZsPLUSnOLKfesthdhJpW49KHmre0YwVeBJdAXlhbXJYxm
XpJU+EYuQHGh9BORQJHzSbDUds7DTjWEg3SPbTqC1nw76vJP9NhIndb7R0w0QE6H
GwR2p5AV9spu1CrnzXwzhgBDA9e+SKF1GUgiduUx6RAVBA89a1QASgc/u7bVwLgc
TqOE2iRUCDKr+UMtH7LTfjrgFJCfpzVJ7wWEyZg5+AhKvWn50VNLqszrgBy4Xntw
j6RNnQLwO5v2SQbPXErBFeisw7ghPWmUnb8CZoYf3h9ega3XVkvIXWdXVuXWRkQh
tcLTdlRZgwef7H9iCLsV8JCheCgLsiQhNPOGfrYgXR6B1rd0mHsIbXJVB9xSggTw
u8FY18qPFstASOBIupU6Xy/ORmhOSG3T77hbRyCGSSO3K0jbezviMQyq/vfytLZ4
3C/ByOvocm1MPgKMt2mgkcLjuTdjzfP7pMYgMGxGHNvKJccs5oiKmIk4YOO/8GI0
vmihZm3QSXtv8jJ4TLdqPxpS9QQcj0Fggu0ZN+G2SjJdlUwDrwKtlOGWKda4DrwL
7TVelS4sqIUxHOHSOkBzC4lh2Qkmn3jVdNjkG3zM3Ub5fzWcBexpjNyzydZO2G9B
WjuEwV3wufw833Nu8rd9N079CtmMr/OpZWcvhUb4LT8AA+KHlbjIKZ2NPMTI/S5V
5hB4/0qNs9ZnPO7W0QHssstCEMdIRmnuYQDO1Lx1GUA13dp6LyEkb3fZeoGF+e8C
a7a9f0Bczkqcwij01fD1rLsP40RgPZ5bfmvSL2PcnbxvVOMOXTko2mldCJGWqjwP
wSTRWZPbBvwtoxVLye0/zivQK0WPpe1ESnJ4y3kmvla3leeI4ZOkuwfZfpN4xSha
nUW3uQddXp6c2h7vG+rllDH19HWtoxkQEpIXyR3QigQBwN4kWe0rd35Y+sn5nIDg
x0g8jlCU/3mNfk6PiheQ0UOlqzPu3sbaZ6rYjQ6SS/gIj9pvBCK97p7+rAxKUawR
-----END RSA PRIVATE KEY----- }}
        script: cd /home/docker_/django_docker_repo && git pull origin main && docker-compose down && docker rmi django_landingpage:latest || true && docker-compose build && docker-compose up -d
